name: cognit_app_all_accesd

description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.1
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  cloud_firestore: ^6.7.1
  firebase_storage: ^13.4.5
  flutter_launcher_icons: ^0.14.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/icon/cognit_icon.png


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/cognit_icon.png"

  # Add assets later when robot image is ready
  # assets:
  #   - assets/images/cognit_robot.png