// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWqV_Xd2cjeW9K756Jl7AixozbZBIT5YY',
    appId: '1:645040726099:web:6a641f2509cedc07bba6a6',
    messagingSenderId: '645040726099',
    projectId: 'cognit-infinity',
    authDomain: 'cognit-infinity.firebaseapp.com',
    storageBucket: 'cognit-infinity.firebasestorage.app',
    measurementId: 'G-ES1KN5Q314',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAQxwFPq4csKPBTIJybWfN_H9qW8MPNJk',
    appId: '1:645040726099:android:3d353698180f966cbba6a6',
    messagingSenderId: '645040726099',
    projectId: 'cognit-infinity',
    storageBucket: 'cognit-infinity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnskFKTaIOCgkj8_EHpDNiR4DQlMUsSz4',
    appId: '1:645040726099:ios:b9771eba37f7a42fbba6a6',
    messagingSenderId: '645040726099',
    projectId: 'cognit-infinity',
    storageBucket: 'cognit-infinity.firebasestorage.app',
    iosBundleId: 'com.example.cognitAppAllAccesd',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnskFKTaIOCgkj8_EHpDNiR4DQlMUsSz4',
    appId: '1:645040726099:ios:b9771eba37f7a42fbba6a6',
    messagingSenderId: '645040726099',
    projectId: 'cognit-infinity',
    storageBucket: 'cognit-infinity.firebasestorage.app',
    iosBundleId: 'com.example.cognitAppAllAccesd',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWqV_Xd2cjeW9K756Jl7AixozbZBIT5YY',
    appId: '1:645040726099:web:c79898f68c01cde7bba6a6',
    messagingSenderId: '645040726099',
    projectId: 'cognit-infinity',
    authDomain: 'cognit-infinity.firebaseapp.com',
    storageBucket: 'cognit-infinity.firebasestorage.app',
    measurementId: 'G-5Y19W5LXNX',
  );
}
